monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - exchange_rates

when@dev:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
                max_files: 30
                filename_format: '{filename}-{date}'
                date_format: Y-m-d
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
            exchange_rates:
                type: rotating_file
                path: "%kernel.logs_dir%/exchange_rates.log"
                level: info
                channels: ["exchange_rates"]
                max_files: 30
                filename_format: '{filename}-{date}'
                date_format: Y-m-d

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
                max_files: 30
                filename_format: '{filename}-{date}'
                date_format: Y-m-d
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
            exchange_rates:
                type: rotating_file
                path: "%kernel.logs_dir%/exchange_rates.log"
                level: info
                channels: ["exchange_rates"]
                max_files: 30
                filename_format: '{filename}-{date}'
                date_format: Y-m-d
                formatter: monolog.formatter.json
