# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    binance.api_url: '%env(BINANCE_API_URL)%'
    binance.api_timeout: '%env(int:BINANCE_API_TIMEOUT)%'
    app.get_rates.cache.short_ttl: 300
    app.get_rates.cache.long_ttl: 3600

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Command\UpdateExchangeRatesCommand:
        arguments:
            $exchangeRatesLogger: '@monolog.logger.exchange_rates'

    App\Service\Provider\BinanceProvider:
        arguments:
            $apiUrl: '%binance.api_url%'
            $timeout: '%binance.api_timeout%'
        tags: [ 'exchange_rate_provider' ]

    App\Service\ExchangeRateUpdaterService:
        arguments:
            $providers: !tagged_iterator exchange_rate_provider

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
